### ISSUE TITLE
Proper macOS icon size

### ISSUE THREAD

**Issue by Hacksore** [GlitchTech-Developments/GraphiteDesktop#14]
right now it is not the right size and looks wonky.

<img width="324" alt="image" src="https://github.com/GlitchTech-Developments/GraphiteDesktop/assets/996134/3da072b6-7cbc-4f8f-9b08-dddc20023d7d">

I use a figma template for mine, not sure which one but there are a bunch to pick from.

https://www.figma.com/community/search?resource_type=mixed&sort_by=relevancy&query=macos+icon&editor_type=all&price=all&creators=all

**Comment by JesseKoldewijn** [comment]
Hey man, 
thanks for bringing this up first of all! 

I'll have a look into it ASAP!

**Comment by JesseKoldewijn** [comment]
Btw, @Hacksore I saw you were trying to get the universal MacOS build to work and saw you set the build target back to "all". The core reason I've explicitly set the targets is because of an issue within the Tauri build pipeline when trying to target AppImage. Just to clear that possible question up ;)

**Comment by JesseKoldewijn** [comment]
@Hacksore icon should be fixed in release 0.5.4 which is up as of a couple of minutes ago. Feel free to open a new issue if you find out this fix was not sufficient (since I don't have a mac to test this on). Still pushing release since its not breaking.
